### PR TITLE
release gem v0.3.1

### PR DESCRIPTION
**Pull request by wtnabe**
update below
- Rakefile
- Manifest.txt

Now, we can generate gem with current toolchain !

### CODE REVIEW

**Comment by mootoh** [comment]
should be good :+1:

**Comment by wtnabe** [comment]
release, please :pray:

**Comment by mootoh** [comment]
Released 0.3.1, thanks @wtnabe  https://rubygems.org/gems/rtmilk/versions/0.3.1

**Comment by wtnabe** [comment]
YATTA !! :+1:

**Pull request merged**
